site_name: OHAI - Open Hardware Assembly Instructions
site_url: https://ohai.opulo.io/
repo_url: https://github.com/opulo-inc/lumenpnp/
edit_uri: https://github.com/opulo-inc/ohai/edit/main/docs
copyright: LumenPnP and its related works are proudly released under the CERN-OHL-W-2.0 license - Opulo Inc 2024
extra_css: [stylesheets/extra.css]

#plugins:
#  - glightbox

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html

theme:
  name: material
  logo: img/opulo.png
  favicon: img/favicon.ico
  font:
    text: Lexend
    # code: Ubuntu Mono
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - toc.follow
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.tracking

nav:
  - Home: index.md
  - LumenPnP:
        - Introduction: lumen/index.md
        - X Gantry: lumen/x-gantry/index.md
        - Y Gantry: lumen/y-gantry/index.md
        - Feeder Rail (Front and Rear): lumen/feeder-rail/index.md
        - Drag Chain: lumen/drag-chain/index.md
        - Control Box: lumen/control-box/index.md
        - Staging Plate: lumen/staging-plate/index.md
        - Getting Started Kit (FTP): misc/ftp-kit/index.md
        - Tool Kit: lumen/tool-kit/index.md
        - Additional Parts: lumen/additional-parts/index.md
        - Packaging: lumen/pack-out/index.md
 
  - Feeder:
        - Overview: feeder8/index.md
        - PCB: feeder8/pcb/index.md
        - Peel Motor Assembly: feeder8/peel-motor/index.md
        - Drive Wheel Assembly: feeder8/indexing-wheel/index.md
        - Peel Gear Box: feeder8/peel-gear-frame/index.md
        - Frame Assembly: feeder8/feeder-frame-8mm-asm/index.md
        - Final Assembly: feeder8/assembly/index.md
        - OQC: feeder8/oqc/index.md
        - Packaging: feeder8/packout/index.md

  - Feeder Connection Kit:
        - Introduction: feeder-connection-kit/index.md
        - Feeder Blade PCBA: feeder-connection-kit/panelized-feeder-slot/index.md
        - Feeder Blade Set Final Assembly: feeder-connection-kit/slot-set/index.md
        - Feeder Accessory Preparation: feeder-connection-kit/accessories/index.md
        - Packaging: feeder-connection-kit/packout/index.md

  - v4 Upgrade Parts:
        - Overview: v4-upgrade-parts/index.md
        - LumenPnP v4 Control Box: lumen/control-box/index.md
        - LumenPnP v4 Toolhead Kit: v4-upgrade-parts/lumenpnp-toolhead-asm-v4/index.md
        - LumenPnP v4 Drag Chain Assembly Kit: v4-upgrade-parts/drag-chain-assembly-kit-v4/index.md
        - (WIP) LumenPnP v4 Endstop PCB Set: v4-upgrade-parts/endstop-set-v4/index.md
        - LumenPnP v4 Frame Cable Harness Set: v4-upgrade-parts/frame-cable-harness-set/index.md
        - LumenPnP v4 USB Camera Set: v4-upgrade-parts/lumenpnp-v4-camera-set/index.md

  - v2/v3 Spare Parts:
        - Overview: v2-v3_spare_parts/index.md
        - LumenPnP v2/v3 Toolhead Kit: v2-v3_spare_parts/lumenpnp-toolhead-asm-v3/index.md
        - LumenPnP v2/v3 Vacuum Pump and Valve Set: v2-v3_spare_parts/vac-and-valve-set-v3/index.md
        - LumenPnP v2/v3 Replacement PCB Kit: v2-v3_spare_parts/v3-pcb-kit/index.md

  - LumenPnP Accessories:
        - Overview: lumenpnp-accessories/index.md
        - Staging Plate: lumenpnp-accessories/staging-plate-set/index.md
        - Getting Started Kit: lumenpnp-accessories/ftp-kit/index.md
        - Strip Feeder: lumenpnp-accessories/strip-feeder/index.md
        - Paste Extruder Kit: lumenpnp-accessories/paste-extruder/index.md

  - DIY Components:
        - Overview: diy-components/index.md
        - LumenPnP CP40 Nozzle Set: lumen/additional-parts/#nozzle-rack
        - LumenPnP Z-Axis Linear Rail Set: diy-components/z-axis-linear-rail-set/index.md
        - LumenPnP 24vDC 6A Power Supply: diy-components/6A-power-supply-with-cord/index.md
        - LumenPnP Frame Kit: diy-components/frame-kit/index.md
        - LumenPnP GT2 Belt and Pulley Kit: diy-components/gt2-belt-and-pulley-kit/index.md
        - MGN12H Linear Rail Kit: diy-components/MGN12H-linear-rail-kit/index.md
        - NEMA 17 Stepper Motor (4-Pack): diy-components/NEMA-17-stepper-motor 4-pack/index.md
        - LumenPnP Ring Light Set: diy-components/ring-light-set/index.md
        - LumenPnP Datum Board: diy-components/datum-board-kit/index.md
        - Feeder Part Kit: diy-components/feeder-part-kit/index.md
        - Control Box: diy-components/control-box/index.md
        - Fastener Kit: diy-components/fastener-kit/index.md
  
  - Operations:
        - Overview: operations/index.md
        - Ordering from LCSC: operations/purchasing-from-lcsc/index.md
        - Print Farm: operations/print-farm/index.md
        - Order Fulfillment SOP: operations/order-fulfillment/