site_name: OHAI - Open Hardware Assembly Instructions
site_url: https://ohai.opulo.io/
repo_url: https://github.com/opulo-inc/ohai/
copyright: LumenPnP and its related works are proudly released under the GPL-3.0 license - Opulo Inc 2023
extra_css: [stylesheets/extra.css]

#plugins:
#  - glightbox

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html

theme:
  name: material
  logo: img/opulo.png
  favicon: img/favicon.ico
  font:
    text: Roboto
  features:
    - navigation.footer
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.tracking


nav:
  - OHAI: index.md
  - LumenPnP (v3.1):
        - Introduction: lumen/index.md
        - Motherboard: lumen/mobo/index.md
        - X Gantry: lumen/x-gantry/index.md
        - Y Gantry: lumen/y-gantry/index.md
        - Front/Rear Feeder Rail: lumen/feeder-rail/index.md
        - Drag Chain: lumen/drag-chain/index.md
        - Staging Plate: lumen/staging-plate/index.md
        - Getting Started Kit: misc/ftp-kit/index.md
        - Tool Kit: lumen/tool-kit/index.md
        - Additional Parts: lumen/additional-parts/index.md
        - Packaging: lumen/pack-out/index.md
 
  - 8mm Feeder:
        - Overview: feeder8/index.md
        - PCB: feeder8/pcb/index.md
        - Peel Motor Assembly: feeder8/peel-motor/index.md
        - Drive Wheel Assembly: feeder8/indexing-wheel/index.md
        - Peel Gear Box: feeder8/peel-gear-frame/index.md
        - Frame Assembly: feeder8/feeder-frame-8mm-asm/index.md
        - Final Assembly: feeder8/assembly/index.md
        - OQC: feeder8/oqc/index.md
        - Packaging: feeder8/packout/index.md

  - Feeder Connection Kit:
        - Introduction: feeder-connection-kit/index.md
        - Feeder Slot PCBA: feeder-connection-kit/panelized-feeder-slot/index.md
        - Feeder Slot Set Final Assembly: feeder-connection-kit/slot-set/index.md
        - Feeder Accessory Preparation: feeder-connection-kit/accessories/index.md
        - Packaging: feeder-connection-kit/packout/index.md

  - Misc Products:
        - Overview: misc/index.md
        - LumenPnP Toolhead Assembly: misc/lumenpnp-toolhead-asm/index.md
        - LumenPnP Vacuum Pump and Valve Set: misc/vac-and-valve-set/index.md
        - Packaged CP40 Nozzle Set: misc/cp40-noz-set/index.md
        - LumenPnP PCB Kit: misc/v3-pcb-kit/index.md
        - Staging Plate 1/2 Pack: misc/staging-plate-set/index.md
        - Getting Started Kit: misc/ftp-kit/index.md
        - Vacuum Sensor Upgrade Kit: misc/rev3-vac-interposer/index.md
        - Feeder Part Kit: misc/feeder-part-kit/index.md